modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "elementalenergistics"
version = "${mod_version}"
displayName = "Elemental Energistics"
authors = "WaterFoxR"
description = '''${mod_description}'''


[[dependencies.elementalenergistics]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.elementalenergistics]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.elementalenergistics]]
modId = "dpanvil"
mandatory = true
versionRange = "[1.20.1-5.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.elementalenergistics]]
modId = "elementalcraft"
mandatory = true
versionRange = "[1.20.1-6.0.1,)"
ordering = "NONE"
side = "BOTH"